const test=require('node:test'),assert=require('node:assert/strict'),{planPhoto}=require('./photo-state');
const a='a'.repeat(64),b='b'.repeat(64),c='c'.repeat(64);
const args={sourceContactId:'source',uid:'target',primaryUrl:'https://example.test/new',target:{uid:'target',state:'readable',contentHash:a,propertyHash:a},download:{requestedUrl:'https://example.test/new',statusCode:200,decoded:true,contentHash:b,mime:'image/jpeg',width:200,height:200},baseline:{version:1,sourceContactId:'source',uid:'target',sourceContentHash:a,targetPropertyHash:a}};
const run=patch=>planPhoto({...args,...patch});
test('changed source and unchanged target permits replacement preparation',()=>assert.equal(run({}).action,'replace'));
test('403 and 404 preserve existing image',()=>{for(const statusCode of [403,404])assert.equal(run({download:{...args.download,statusCode}}).action,'preserve');});
test('missing primary never clears existing image',()=>assert.equal(run({primaryUrl:null}).action,'preserve'));
test('URL rotation with identical content does not write',()=>assert.equal(run({download:{...args.download,contentHash:a}}).action,'unchanged'));
test('same URL with new image content can update',()=>assert.equal(run({}).reason,'source_changed_target_unchanged'));
test('independent iCloud change is held',()=>assert.equal(run({target:{...args.target,contentHash:c,propertyHash:c}}).reason,'target_changed_since_baseline'));
test('working photo without baseline is protected',()=>assert.equal(run({baseline:null}).reason,'replacement_needs_baseline'));
test('confirmed missing photo may be filled without replacing anything',()=>assert.equal(run({baseline:null,target:{uid:'target',state:'missing',propertyHash:a}}).action,'fill'));
test('independent target removal is held, not silently restored',()=>assert.equal(run({target:{uid:'target',state:'missing',propertyHash:c}}).action,'hold'));
test('unreadable is not treated as absent',()=>assert.equal(run({baseline:null,target:{uid:'target',state:'unreadable',propertyHash:a}}).action,'hold'));
test('unknown native photo availability holds',()=>assert.equal(run({target:{uid:'target',state:'unknown',propertyHash:a}}).reason,'target_not_verified'));
test('HTML errors or incomplete decode evidence never become images',()=>{for(const change of [{mime:'text/html'},{decoded:false},{contentHash:null},{width:0},{height:99999999}])assert.equal(run({download:{...args.download,...change}}).action,'hold');});
test('stale download cannot replace current primary',()=>assert.equal(run({download:{...args.download,requestedUrl:'https://example.test/old'}}).reason,'primary_not_downloaded'));
test('wrong contact baseline or readback identity rejects',()=>{assert.throws(()=>run({baseline:{...args.baseline,uid:'wrong'}}));assert.throws(()=>run({target:{...args.target,uid:'wrong'}}));});
test('unsafe URL and missing hashes reject',()=>{assert.throws(()=>run({primaryUrl:'http://example.test/image'}));assert.throws(()=>run({target:{...args.target,contentHash:null}}));});
